
CREATE DATABASE software_vida_financeira;

USE software_vida_financeira;

CREATE TABLE cliente (
NOME_COMPLETO VARCHAR(75) NOT NULL,
CPF VARCHAR(11) NOT NULL,
EMAIL VARCHAR(75) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
DATA_NASCIMENTO DATE,
PROFISSAO VARCHAR(50),
GENERO ENUM('M', 'F'),
PRIMARY KEY (CPF, EMAIL)
);

