
CREATE DATABASE software_vida_financeira;

USE software_vida_financeira;

CREATE TABLE cliente (
NOME_COMPLETO VARCHAR(75) NOT NULL,
CPF VARCHAR(11) NOT NULL,
EMAIL VARCHAR(75) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
DATA_NASCIMENTO DATE,
PROFISSAO VARCHAR(50),
GENERO ENUM('M', 'F'),
PRIMARY KEY (CPF)
);

/* FALTA TERMINAR - "Cada cliente poderá cadastrar somente um endereço"
CREATE TABLE endereco (
CEP VARCHAR(8),
RUA VARCHAR(50) NOT NULL,
NUMERO SMALLINT UNSIGNED NOT NULL,
COMPLEMENTO VARCHAR(15),
BAIRRO VARCHAR(50) NOT NULL,
CIDADE VARCHAR(50) NOT NULL,
ESTADO VARCHAR(50) NOT NULL,
PAÍS VARCHAR(50) NOT NULL
);*/

CREATE TABLE conta_corrente (
CODIGO_DO_BANCO VARCHAR(8) NOT NULL,
NUMERO_DA_CONTA VARCHAR(5) NOT NULL,
AGENCIA VARCHAR(4) NOT NULL,
APELIDO VARCHAR(15) NOT NULL,
SALDO FLOAT,
PRIMARY KEY (CODIGO_DO_BANCO, NUMERO_DA_CONTA)
);

CREATE TABLE movimentacao_financeira (
VALOR FLOAT NOT NULL,
DATA DATE NOT NULL,
CODIGO_DO_BANCO VARCHAR(8) NOT NULL,
NUMERO_DA_CONTA VARCHAR(5) NOT NULL,
CATEGORIA VARCHAR(50) NOT NULL
);

ALTER TABLE movimentacao_financeira ADD CONSTRAINT FK_CONTA_CORRENTE 
FOREIGN KEY (CODIGO_DO_BANCO, NUMERO_DA_CONTA) 
REFERENCES conta_corrente(CODIGO_DO_BANCO, NUMERO_DA_CONTA); 
